#!/usr/bin/env sh
if ! head -1 "$1" | grep -qE "^(feat|fix|refactor|chore)(\(.+?\))?: .{1,}$"; then
    echo "Aborting commit. Commit message must include prefix (feat, fix, refactor or chore)." >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,100}$"; then
    echo "Aborting commit. Commit message is longer than 100 characters." >&2
    exit 1
fi